/*
    UILaunchOptionsDialog.cpp
    

*/
//UILaunchOptionsDialog.cpp generated by CBTek Solutions on 02-24-2017 at 11:07:46 PM

#include "UILaunchOptionsDialog.h"
#include "ui_UILaunchOptionsDialog.h"

namespace oig {
namespace ratstats {
namespace ui {


UILaunchOptionsDialog::UILaunchOptionsDialog(QWidget *parent) :
    QDialog(parent),
    m_ui(new Ui_UILaunchOptionsDialog)
{
    m_ui->setupUi(this);
}




UILaunchOptionsDialog::~UILaunchOptionsDialog()
{
    delete m_ui;
}
}}}//end namespace

