/*
    UIRStatsSettingsManager.cpp
    

*/
//UIRStatsSettingsManager.cpp generated by CBTek Solutions on 02-03-2017 at 02:17:32 AM

#include <QSpinBox>
#include <QLabel>
#include <QPushButton>
#include <QLineEdit>
#include <QTableWidget>
#include <QFrame>
#include <QHBoxLayout>
#include <QMessageBox>

#include "UIRStatsSettingsManager.h"
#include "ui_UIRStatsSettingsManager.h"
#include "utility/inc/StringUtils.hpp"

#include "UIRStatsUtils.hpp"
#include "UIRStatsScriptProviderConfigDialog.h"

using namespace oig::ratstats::utils;
using namespace cbtek::common::utility;

namespace oig {
namespace ratstats {
namespace ui {

UIRStatsSettingsManager::UIRStatsSettingsManager(QWidget *parent) :
    QDialog(parent),
    m_ui(new Ui_UIRStatsSettingsManager)
{
    m_ui->setupUi(this);
    onInitScriptProviders();
    onInitThemes();
    onInitKeyBindings();
    connect(m_ui->m_btnClose,SIGNAL(clicked(bool)),this,SLOT(onClose()));
    m_removeIcon = UIRStatsUtils::getIcon("img_remove.png");
    m_editIcon = UIRStatsUtils::getIcon("img_edit.png");
    m_exitIcon = UIRStatsUtils::getIcon("img_exit.png");
    m_addIcon = UIRStatsUtils::getIcon("img_add.png");
    m_ui->m_btnClose->setIcon(m_exitIcon);
    m_ui->m_btnNewScriptProvider->setIcon(m_addIcon);
}

UIRStatsSettingsManager::~UIRStatsSettingsManager()
{
    delete m_ui;
}

void UIRStatsSettingsManager::onClose()
{    
    this->close();
}

void UIRStatsSettingsManager::onInitScriptProviders()
{
    m_props = RStatsUtils::getScriptProviderPropertiesList();
    QTableWidget * table = m_ui->m_tblScriptProviders;
    table->clear();
    table->horizontalHeader()->hide();
    table->setRowCount(m_props.size());
    table->setColumnCount(1);
    int row = 0;
    for(const RStatsScriptProviderProperties & prop : m_props)
    {
        QHBoxLayout * layout = new QHBoxLayout;
        QFrame * cellFrame = new QFrame;
        QLabel * label = new QLabel;
        QPushButton * deleteButton = new QPushButton;
        QPushButton * editButton = new QPushButton;
        deleteButton->setIconSize(QSize(32,32));
        editButton->setIconSize(QSize(32,32));
        deleteButton->setIcon(m_removeIcon);
        editButton->setIcon(m_editIcon);
        label->setText(QString::fromStdString(prop.getName()));
        layout->addWidget(label);
        layout->addWidget(editButton);
        layout->addWidget(deleteButton);
        editButton->setProperty("index",row);
        deleteButton->setProperty("index",row);
        m_editButtons.addButton(editButton);
        m_deleteButtons.addButton(deleteButton);
        cellFrame->setLayout(layout);
        table->setCellWidget(row,0,cellFrame);
        ++row;

    }
    connect(&m_editButtons,SIGNAL(buttonClicked(QAbstractButton*)),this,SLOT(onEditScriptProvider(QAbstractButton*)));
    connect(&m_deleteButtons,SIGNAL(buttonClicked(QAbstractButton*)),this,SLOT(onDeleteScriptProvider(QAbstractButton*)));
    connect(m_ui->m_btnNewScriptProvider,SIGNAL(clicked(bool)),this,SLOT(onAddScriptProvider()));

}

void UIRStatsSettingsManager::onInitThemes()
{

}

void UIRStatsSettingsManager::onInitKeyBindings()
{

}

void UIRStatsSettingsManager::onEditScriptProvider(QAbstractButton *button)
{
    int index = button->property("index").toInt();
    RStatsScriptProviderProperties props = m_props[index];
    UIRStatsScriptProviderConfigDialog(props).exec();
}

void UIRStatsSettingsManager::onDeleteScriptProvider(QAbstractButton *button)
{
    int index = button->property("index").toInt();
    RStatsScriptProviderProperties props = m_props[index];
    int answer = QMessageBox::question(this,"Remove Script Provider?", "Are you sure you want to remove the script provider \""+QString::fromStdString(props.getName())+"\"",QMessageBox::Yes,QMessageBox::No);
    if (answer == QMessageBox::Yes)
    {
        m_ui->m_tblScriptProviders->removeCellWidget(index,0);
        props.removeConfig();
    }
    onInitScriptProviders();
}

void UIRStatsSettingsManager::onAddScriptProvider()
{
   RStatsScriptProviderProperties props;
   UIRStatsScriptProviderConfigDialog(props).exec();
}
}}}//end namespace

