/*
    UIRStatsSVA.cpp
    

*/
//UIRStatsSVA.cpp generated by CBTek Solutions on 01-28-2017 at 10:39:41 PM

#include "UIRStatsSVA.h"
#include "ui_UIRStatsSVA.h"

namespace oig {
namespace ratstats {
namespace modules {
namespace sva {


UIRStatsSVA::UIRStatsSVA(QWidget *parent) :
    QMainWindow(parent),
    m_ui(new Ui_UIRStatsSVA)
{
    m_ui->setupUi(this);    
    connect(m_ui->m_btnImportData,SIGNAL(clicked(bool)),this,SLOT(onImportInputData()));
    connect(m_ui->m_btnExportData,SIGNAL(clicked(bool)),this,SLOT(onExportInputData()));
    connect(m_ui->m_btnHelp,SIGNAL(clicked(bool)),this,SLOT(onHelp()));
    connect(m_ui->m_btnExit,SIGNAL(clicked(bool)),this,SLOT(onExit()));
    connect(m_ui->m_btnContinue,SIGNAL(clicked(bool)),this,SLOT(onContinue()));
}

UIRStatsSVA::~UIRStatsSVA()
{
    delete m_ui;
}

void UIRStatsSVA::onContinue()
{

}

void UIRStatsSVA::onExit()
{

}

void UIRStatsSVA::onImportInputData()
{

}

void UIRStatsSVA::onExportInputData()
{

}

void UIRStatsSVA::onHelp()
{

}

void UIRStatsSVA::onSetOutputFolder()
{

}

void UIRStatsSVA::onSetPrinterOptions()
{

}
}}}}//end namespace

