/*
    UISVA.cpp
    

*/
//UISVA.cpp generated by CBTek Solutions on 01-28-2017 at 10:39:41 PM

#include "UISVA.h"
#include "ui_UISVA.h"

namespace oig {
namespace ratstats {
namespace sva {


UISVA::UISVA(QWidget *parent) :
    QMainWindow(parent),
    m_ui(new Ui_UISVA)
{
    m_ui->setupUi(this);
    connect(m_ui->m_btnSetOutputFolder,SIGNAL(clicked(bool)),this,SLOT(onSetOutputFolder()));
    connect(m_ui->m_btnImportData,SIGNAL(clicked(bool)),this,SLOT(onImportInputData()));
    connect(m_ui->m_btnExportData,SIGNAL(clicked(bool)),this,SLOT(onExportInputData()));
    connect(m_ui->m_btnHelp,SIGNAL(clicked(bool)),this,SLOT(onHelp()));
    connect(m_ui->m_btnExit,SIGNAL(clicked(bool)),this,SLOT(onExit()));
    connect(m_ui->m_btnContinue,SIGNAL(clicked(bool)),this,SLOT(onContinue()));
}

UISVA::~UISVA()
{
    delete m_ui;
}

void UISVA::onContinue()
{

}

void UISVA::onExit()
{

}

void UISVA::onImportInputData()
{

}

void UISVA::onExportInputData()
{

}

void UISVA::onHelp()
{

}

void UISVA::onSetOutputFolder()
{

}

void UISVA::onSetPrinterOptions()
{

}
}}}//end namespace

