/*
    RStatsCSVWorkbookStream.cpp
    

*/
//----------------------------------------
//RStatsCSVWorkbookStream.cpp generated by CBTek Solutions on 02-01-2017 at 11:54:13 PM
//----------------------------------------
#include "RStatsCSVWorkbookStream.h"

namespace oig {
namespace ratstats {
namespace utils {


RStatsCSVWorkbookStream::RStatsCSVWorkbookStream(const std::string &filePath)
{
    m_filePath = filePath;
}

void RStatsCSVWorkbookStream::write(const RStatsWorkbook &workbook)
{

}

RStatsWorkbook RStatsCSVWorkbookStream::read()
{

}
RStatsCSVWorkbookStream::~RStatsCSVWorkbookStream()
{

}




}}}//end namespace


