/*
    UIRStatsShortcut.cpp
    

*/
//----------------------------------------
//UIRStatsShortcut.cpp generated by sunefusion on 03-04-2017 at 02:51:46 PM
//----------------------------------------
#include "UIRStatsShortcut.h"

namespace oig {
namespace ratstats {
namespace ui {

UIRStatsShortcut::UIRStatsShortcut(const QKeySequence &sequence, QWidget *parent) : QShortcut(sequence,parent)
{
    connect(this,SIGNAL(activated()),this,SLOT(onActivated()));
}

UIRStatsShortcut::~UIRStatsShortcut()
{

}

void UIRStatsShortcut::onActivated()
{
    emit activated(this);
}




}}}//end namespace


