/*
    UIGooeyFiAppBuilder.cpp
    
MIT License

Copyright (c) 2016 cbtek

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/
//UIGooeyFiAppBuilder.cpp generated by sunefusion on 02-25-2017 at 09:54:42 PM

#include "UIGooeyFiAppBuilder.h"
#include "ui_UIGooeyFiAppBuilder.h"

#include <QListWidgetItem>
#include <QTableWidget>
#include <QLineEdit>
#include <QPushButton>
#include <QSpinBox>
#include <QGridLayout>
#include <QLabel>
#include <QPlainTextEdit>

namespace cbtek {
namespace products {
namespace gooeyfi {
namespace builder {


UIGooeyFiAppBuilder::UIGooeyFiAppBuilder(QWidget *parent) :
    QDialog(parent),
    m_ui(new Ui_UIGooeyFiAppBuilder)
{
    m_ui->setupUi(this);
    m_ui->m_lstSourceWidgets->addItem("Text Input Field");
    m_ui->m_lstSourceWidgets->addItem("Password Input Field");
    m_ui->m_lstSourceWidgets->addItem("Multiline Text Input Field");
    m_ui->m_lstSourceWidgets->addItem("Integer Numeric Field");
    m_ui->m_lstSourceWidgets->addItem("Floating-point Numeric Field");
    m_ui->m_lstSourceWidgets->addItem("File Select Field");
    m_ui->m_lstSourceWidgets->addItem("Folder Select Field");
    m_ui->m_lstSourceWidgets->addItem("CheckBox Field");

    m_ui->m_tblDestinationWidgets->setColumnCount(1);
    m_ui->m_tblDestinationWidgets->horizontalHeader()->setSectionResizeMode(1,QHeaderView::Stretch);
    m_ui->m_tblDestinationWidgets->verticalHeader()->hide();
    m_ui->m_tblDestinationWidgets->horizontalHeader()->hide();
    m_ui->m_tblDestinationWidgets->setGridStyle(Qt::NoPen);
    m_ui->m_tblDestinationWidgets->setSelectionMode(QAbstractItemView::NoSelection);

    connect(m_ui->m_btnAdd,SIGNAL(clicked(bool)), this,SLOT(onAdd()));
}

UIGooeyFiAppBuilder::~UIGooeyFiAppBuilder()
{
    delete m_ui;
}

void UIGooeyFiAppBuilder::onAdd()
{
    QListWidgetItem * selectedItem = m_ui->m_lstSourceWidgets->currentItem();
    if (selectedItem)
    {
        QString key = selectedItem->text().toUpper();
        int row = m_ui->m_tblDestinationWidgets->rowCount();
        m_ui->m_tblDestinationWidgets->setRowCount(row+1);
        QTableWidget * table = m_ui->m_tblDestinationWidgets;
        QGridLayout * layout = new QGridLayout;
        QLineEdit * widgetNameInput = new QLineEdit;
        QLabel * widgetNameLabel = new QLabel("Widget Name");
        QFrame * widgetFrame = new QFrame;
        layout->addWidget(widgetNameLabel,0,0);
        layout->addWidget(widgetNameInput,1,0);

        if (key.contains("TEXT INPUT"))
        {
            QLineEdit * input = new QLineEdit;
            QLabel * inputLabel = new QLabel("Default Text");
            layout->addWidget(inputLabel,0,1);
            layout->addWidget(input,1,1);
        }
        else if (key.contains("PASSWORD INPUT"))
        {
            QLineEdit * input1 = new QLineEdit;
            QLineEdit * input2 = new QLineEdit;
            QLabel * inputLabel1 = new QLabel("Default Password");
            QLabel * inputLabel2 = new QLabel("Default Password (Verify)");
            input1->setEchoMode(QLineEdit::Password);
            input2->setEchoMode(QLineEdit::Password);
            layout->addWidget(inputLabel1,0,1);
            layout->addWidget(inputLabel2,0,2);
            layout->addWidget(input1,1,1);
            layout->addWidget(input2,1,2);
        }
        else if (key.contains("MULTILINE TEXT INPUT"))
        {
            QPlainTextEdit * input = new QPlainTextEdit;
            QLabel * inputLabel = new QLabel("Default Multiline Text");
            layout->addWidget(inputLabel,0,1);
            layout->addWidget(input,1,1);
        }
        else if (key.contains("FILE SELECT"))
        {
            QLabel * fileLabel = new QLabel("Current File Path");
            QLineEdit * fileInput =  new QLineEdit;
            QPushButton * browse = new QPushButton("Browse");
            layout->addWidget(fileLabel,0,1);
            layout->addWidget(fileInput,1,1);
            layout->addWidget(browse,1,2);

        }
        else if (key.contains("FOLDER SELECT"))
        {
            QLabel * fileLabel = new QLabel("Current File Path");
            QLineEdit * fileInput =  new QLineEdit;
            QPushButton * browse = new QPushButton("Browse");
            layout->addWidget(fileLabel,0,1);
            layout->addWidget(fileInput,1,1);
            layout->addWidget(browse,1,2);
        }
        widgetFrame->setLayout(layout);
        table->setCellWidget(row,0,widgetFrame);
        table->setRowHeight(row,64);
        table->horizontalHeader()->setSectionResizeMode(0,QHeaderView::Stretch);
    }
}

void UIGooeyFiAppBuilder::onPreview()
{

}

void UIGooeyFiAppBuilder::onOk()
{

}

void UIGooeyFiAppBuilder::onEdit(QAbstractButton *button)
{

}

void UIGooeyFiAppBuilder::onRemove(QAbstractButton *button)
{

}
}}}}//end namespace

