/*
    UIGooeyFiWidgetDefaults.cpp
    
MIT License

Copyright (c) 2016 cbtek

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/
//UIGooeyFiWidgetDefaults.cpp generated by sunefusion on 02-26-2017 at 01:02:39 PM

#include "UIGooeyFiWidgetDefaults.h"
#include "ui_UIGooeyFiWidgetDefaults.h"

#include <QListWidgetItem>
#include <QTableWidget>
#include <QLineEdit>
#include <QPushButton>
#include <QSpinBox>
#include <QGridLayout>
#include <QLabel>
#include <QPlainTextEdit>

#include "gooeyfi_core/inc/GooeyFiUtils.h"


using namespace cbtek::products::gooeyfi::core;

namespace cbtek {
namespace products {
namespace gooeyfi {
namespace builder {


UIGooeyFiWidgetDefaults::UIGooeyFiWidgetDefaults(const core::GooeyFiWidgetPtr &widget, QWidget *parent) :
    QDialog(parent),
    m_ui(new Ui_UIGooeyFiWidgetDefaults)
{
    m_ui->setupUi(this);
    m_widget = widget;
}


UIGooeyFiWidgetDefaults::~UIGooeyFiWidgetDefaults()
{
    delete m_ui;
}

void UIGooeyFiWidgetDefaults::onInit()
{
    if (m_widget.get())
    {
        if (m_widget->getId() == core::GooeyFiWidgetIdType::Button)
        {
            const GooeyFiButton * button = GooeyFiUtils::getButton(m_widget);
            m_ui->m_lytMain->addWidget(inputLabel,0,0);
            m_ui->m_lytMain->addWidget(inputLabel,0,0);
            switch(button->getType())
            {
                case GooeyFiButtonType::Action:
                {

                }
                break;
            }

            QLineEdit * input = new QLineEdit;
            QLabel * inputLabel = new QLabel("Default Text");
            layout->addWidget(inputLabel,0,1);
            layout->addWidget(input,1,1);
        }
        else if (m_widget->getId() == core::GooeyFiWidgetIdType::TextInput)
        {
            const GooeyFiTextInput * text = GooeyFiUtils::getTextInput(m_widget);

            QLineEdit * input1 = new QLineEdit;
            QLineEdit * input2 = new QLineEdit;
            QLabel * inputLabel1 = new QLabel("Default Password");
            QLabel * inputLabel2 = new QLabel("Default Password (Verify)");
            input1->setEchoMode(QLineEdit::Password);
            input2->setEchoMode(QLineEdit::Password);
            layout->addWidget(inputLabel1,0,1);
            layout->addWidget(inputLabel2,0,2);
            layout->addWidget(input1,1,1);
            layout->addWidget(input2,1,2);
        }
        else if (m_widget->getId() == core::GooeyFiWidgetIdType::PathBrowser)
        {
            const GooeyFiPathBrowser * path = GooeyFiUtils::getPathBrowser(m_widget);

            QPlainTextEdit * input = new QPlainTextEdit;
            QLabel * inputLabel = new QLabel("Default Multiline Text");
            layout->addWidget(inputLabel,0,1);
            layout->addWidget(input,1,1);
        }
//        else if (key.contains("FILE SELECT"))
//        {
//            QLabel * fileLabel = new QLabel("Current File Path");
//            QLineEdit * fileInput =  new QLineEdit;
//            QPushButton * browse = new QPushButton("Browse");
//            layout->addWidget(fileLabel,0,1);
//            layout->addWidget(fileInput,1,1);
//            layout->addWidget(browse,1,2);

//        }
//        else if (key.contains("FOLDER SELECT"))
//        {
//            QLabel * fileLabel = new QLabel("Current File Path");
//            QLineEdit * fileInput =  new QLineEdit;
//            QPushButton * browse = new QPushButton("Browse");
//            layout->addWidget(fileLabel,0,1);
//            layout->addWidget(fileInput,1,1);
//            layout->addWidget(browse,1,2);
//        }
    }
}
}}}}//end namespace

