/*
    UIRStatsModuleEditor.cpp
    

*/
//UIRStatsModuleEditor.cpp generated by CBTek Solutions on 02-03-2017 at 02:19:12 AM

#include "UIRStatsModuleEditor.h"
#include "ui_UIRStatsModuleEditor.h"

namespace oig {
namespace ratstats {
namespace main {

UIRStatsModuleEditor::UIRStatsModuleEditor(QWidget *parent) :
    QDialog(parent),
    m_ui(new Ui_UIRStatsModuleEditor)
{
    m_ui->setupUi(this);
    //connect(m_ui->m_,SIGNAL(clicked(bool)),this,SLOT(onCancel()));
}

UIRStatsModuleEditor::~UIRStatsModuleEditor()
{
    delete m_ui;
}

void UIRStatsModuleEditor::onCancel()
{
    this->close();
}

void UIRStatsModuleEditor::onSave()
{
    QString exe = m_ui->m_cmbExe->currentText();
    QString name = m_ui->m_txtDisplayName->text();
    QString icon = m_ui->m_cmbIcon->currentText();
//    QShortcut shortcut;
//    shortcut.setKey(m_ui->m_scKeyShortcut->keySequence());
    QString args,group;
    emit moduleSaved(name,group,exe,args,icon);
    this->close();
}
}}}//end namespace

