/*
    UIRStatsModuleManager.cpp
    

*/
//UIRStatsModuleManager.cpp generated by CBTek Solutions on 02-03-2017 at 02:13:29 AM

#include "UIRStatsModuleManager.h"
#include "ui_UIRStatsModuleManager.h"

namespace oig {
namespace ratstats {
namespace main {


UIRStatsModuleManager::UIRStatsModuleManager(QWidget *parent) :
    QDialog(parent),
    m_ui(new Ui_UIRStatsModuleManager)
{
    m_ui->setupUi(this);
    connect(m_ui->m_btnCancel,SIGNAL(clicked(bool)),this,SLOT(onCancel()));
}




UIRStatsModuleManager::~UIRStatsModuleManager()
{
    delete m_ui;
}

void UIRStatsModuleManager::onCancel()
{
    this->close();
}
}}}//end namespace

