/*
    UIRStatsSVADataImportWizard.cpp
    

*/
//UIRStatsSVADataImportWizard.cpp generated by cbtek on 03-21-2017 at 12:12:23 PM

#include "UIRStatsSVADataImportWizard.h"
#include "ui_UIRStatsSVADataImportWizard.h"

namespace oig {
namespace ratstats {
namespace modules {
namespace sva {


UIRStatsSVADataImportWizard::UIRStatsSVADataImportWizard(QWidget *parent) :
    QMainWindow(parent),
    m_ui(new Ui_UIRStatsSVADataImportWizard)
{
    m_ui->setupUi(this);
}

UIRStatsSVADataImportWizard::~UIRStatsSVADataImportWizard()
{
    delete m_ui;
}
}}}}//end namespace

