/*
    RStatsAccessWorkbookStream.cpp
    

*/
//----------------------------------------
//RStatsAccessWorkbookStream.cpp generated by CBTek Solutions on 02-01-2017 at 11:54:24 PM
//----------------------------------------
#include "RStatsAccessWorkbookStream.h"

namespace oig {
namespace ratstats {
namespace utils {


RStatsAccessWorkbookStream::RStatsAccessWorkbookStream(const std::string& filePath)
{
    m_filePath = filePath;
}

void RStatsAccessWorkbookStream::write(const RStatsWorkbook &workbook)
{

}

RStatsWorkbook RStatsAccessWorkbookStream::read()
{

}

RStatsAccessWorkbookStream::~RStatsAccessWorkbookStream()
{

}




}}}//end namespace


